"""Base

Revision ID: 8ac29d494c5f
Revises: 
Create Date: 2026-08-28 12:40:59.483192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8ac29d494c5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('AccountID', sa.Integer(), nullable=False),
    sa.Column('Username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('Email', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('Phone', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('Hashed_Password', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('Birthdate', sa.Date(), nullable=False),
    sa.Column('Occupation', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('AccountID'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Phone'),
    sa.UniqueConstraint('Username')
    )
    op.create_table('dataset',
    sa.Column('DatasetID', sa.Integer(), nullable=False),
    sa.Column('Name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('Description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('File_Path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('File_Format', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('Uploaded_Date', sa.DateTime(), nullable=False),
    sa.Column('Last_Save_Date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('DatasetID')
    )
    op.create_table('project',
    sa.Column('ProjectID', sa.Integer(), nullable=False),
    sa.Column('AccountID', sa.Integer(), nullable=False),
    sa.Column('Name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('Description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Created_At', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['AccountID'], ['account.AccountID'], ),
    sa.PrimaryKeyConstraint('ProjectID')
    )
    op.create_table('rate',
    sa.Column('RateID', sa.Integer(), nullable=False),
    sa.Column('AccountID', sa.Integer(), nullable=False),
    sa.Column('Stars_Number', sa.Integer(), nullable=False),
    sa.Column('Comment', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.ForeignKeyConstraint(['AccountID'], ['account.AccountID'], ),
    sa.PrimaryKeyConstraint('RateID')
    )
    op.create_table('experiment',
    sa.Column('ExperimentID', sa.Integer(), nullable=False),
    sa.Column('ProjectID', sa.Integer(), nullable=False),
    sa.Column('DatasetID', sa.Integer(), nullable=False),
    sa.Column('Name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('Created_At', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['DatasetID'], ['dataset.DatasetID'], ),
    sa.ForeignKeyConstraint(['ProjectID'], ['project.ProjectID'], ),
    sa.PrimaryKeyConstraint('ExperimentID')
    )
    op.create_table('model',
    sa.Column('ModelID', sa.Integer(), nullable=False),
    sa.Column('ExperimentID', sa.Integer(), nullable=False),
    sa.Column('Name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('Version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('Status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('Framework', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('File_Path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('File_Format', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.ForeignKeyConstraint(['ExperimentID'], ['experiment.ExperimentID'], ),
    sa.PrimaryKeyConstraint('ModelID')
    )
    op.create_table('deploy',
    sa.Column('DeployID', sa.Integer(), nullable=False),
    sa.Column('ModelID', sa.Integer(), nullable=False),
    sa.Column('API_URL', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['ModelID'], ['model.ModelID'], ),
    sa.PrimaryKeyConstraint('DeployID')
    )
    op.create_table('inference_log',
    sa.Column('Inference_LogID', sa.Integer(), nullable=False),
    sa.Column('ModelID', sa.Integer(), nullable=False),
    sa.Column('Info', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Made_At', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ModelID'], ['model.ModelID'], ),
    sa.PrimaryKeyConstraint('Inference_LogID')
    )
    op.create_table('model_metric_log',
    sa.Column('Model_Metric_LogID', sa.Integer(), nullable=False),
    sa.Column('ModelID', sa.Integer(), nullable=False),
    sa.Column('Epoch', sa.Integer(), nullable=False),
    sa.Column('Step', sa.Integer(), nullable=False),
    sa.Column('Train_Loss', sa.Float(), nullable=False),
    sa.Column('Eval_Loss', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ModelID'], ['model.ModelID'], ),
    sa.PrimaryKeyConstraint('Model_Metric_LogID')
    )
    op.create_table('test',
    sa.Column('TestID', sa.Integer(), nullable=False),
    sa.Column('ModelID', sa.Integer(), nullable=False),
    sa.Column('Accuracy', sa.Float(), nullable=False),
    sa.Column('Precision', sa.Float(), nullable=False),
    sa.Column('Recall', sa.Float(), nullable=False),
    sa.Column('F1', sa.Float(), nullable=False),
    sa.Column('Final_Train_Loss', sa.Float(), nullable=False),
    sa.Column('Final_Eval_Loss', sa.Float(), nullable=False),
    sa.Column('Mean_Train_Loss', sa.Float(), nullable=False),
    sa.Column('Mean_Eval_Loss', sa.Float(), nullable=False),
    sa.Column('Made_At', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ModelID'], ['model.ModelID'], ),
    sa.PrimaryKeyConstraint('TestID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.drop_table('model_metric_log')
    op.drop_table('inference_log')
    op.drop_table('deploy')
    op.drop_table('model')
    op.drop_table('experiment')
    op.drop_table('rate')
    op.drop_table('project')
    op.drop_table('dataset')
    op.drop_table('account')
    # ### end Alembic commands ###
