name: Backend Tests

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest

    # Prepare postgresql service
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        # Ensure service functionality
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Code Checkout 
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Download packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute connection tests
        env:
          # Pasar la cadena de conexión apuntando al servicio levantado en GitHub Actions
          DATABASE_URL: postgresql+psycopg://test_user:test_password@localhost:5432/test_db
        run: |
          pytest tests/test_db.py -v